version: '3.8'

services:
  whisper:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8033:8000"
    environment:
      - RAY_ADDRESS=local
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: '10gb'
    volumes:
      - ./app:/app/app
    command: tail -f /dev/null
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8033/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3 