services:
  ray_serve:
 #   build: .
    image: ray_whisper:1
    ports:
      - "8033:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 4
              capabilities: [gpu]
    env_file:
      - .env
    shm_size: '10.24gb'
    volumes:
      - ./:/app    # Maps current directory to /app in container
    working_dir: /app
    command: bash -c "cd /app && ray start --head && serve run --host 0.0.0.0 app:transcriber_app"