
services:
  redis:
    image: redis:7.0

    volumes:
      - redis_data:/data

  ray_serve:
    image: ray_whisper:1.1
    ports:
      - "8033:8000"       # Main Serve API port
      - "8265:8265"       # Ray dashboard port
    env_file:
      - .env
    environment:
      - RAY_SERVE_HTTP_HOST=0.0.0.0
      - RAY_SERVE_HTTP_PORT=8000
      - SERVE_PROXY_HOST=0.0.0.0
      - SERVE_PROXY_PORT=8000
      - REDIS_HOST=redis
    shm_size: '10.24gb'
    volumes:
      - ./:/app           # Maps current directory to /app in container
    working_dir: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 4
              capabilities: [gpu]
    command: tail -f /dev/null  #./start.sh
    depends_on:
      - redis

networks:
  whisper_network:
    name: whisper_network
    driver: bridge

volumes:
  redis_data:
