# services:
#   ray_serve:
#     image: ray_whisper:1.1
#     ports:
#       - "8033:8000"
#     deploy:
#       resources:
#         reservations:
#           devices:
#             - driver: nvidia
#               count: 4
#               capabilities: [gpu]
#     env_file:
#       - .env
#     shm_size: '10.24gb'
#     volumes:
#       - ./:/app    # Maps current directory to /app in container
#     working_dir: /app
#     command: bash -c "cd /app && ray start --head --node-ip-address=0.0.0.0 --port=6379 && serve deploy app:transcriber_app && tail -f /dev/null"





#     #bash -c "cd /app && ray start --head && serve run --host 0.0.0.0 app:transcriber_app"


# # docker compose up ray_serve serve run app:transcriber_app

services:
  ray_serve:
    image: ray_whisper:1.1
    ports:
      - "8033:8000"       # Main Serve API port
      - "8265:8265"       # Ray dashboard port
    env_file:
      - .env
    environment:
      - RAY_SERVE_HTTP_HOST=0.0.0.0
      - RAY_SERVE_HTTP_PORT=8000
      - SERVE_PROXY_HOST=0.0.0.0
      - SERVE_PROXY_PORT=8000
    shm_size: '10.24gb'
    volumes:
      - ./:/app           # Maps current directory to /app in container
    working_dir: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 4
              capabilities: [gpu]
    command: ./start.sh

networks:
  whisper_network:
    name: whisper_network
    driver: bridge
