
services:
  ray_serve:
    image: vexaai/ray-whisper:latest
    ports:
      - "${WHISPER_PORT}:8000"       # Main Serve API port
      - "${RAY_DASHBOARD_PORT}:8265"       # Ray dashboard port
    env_file:
      - .env
    environment:
      - RAY_SERVE_HTTP_HOST=0.0.0.0
      - RAY_SERVE_HTTP_PORT=8000
      - SERVE_PROXY_HOST=0.0.0.0
      - SERVE_PROXY_PORT=8000
    shm_size: '10.24gb'
    volumes:
      - ./:/app           # Maps current directory to /app in container
    working_dir: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${SERVER_GPU_COUNT}
              capabilities: [gpu]
    command: ./start.sh

networks:
  whisper_network:
    name: whisper_network
    driver: bridge
